### PR TITLE
Thank you very much veteran. Your review was excellent. I retranslated readme_zh.md

### PR DESCRIPTION
**Pull request by liushuai05**
I'm going to run sqlize_text.go  I have to say your change is good, yes, it's working, and I'm ashamed that the variable names I wrote weren't standard, and the way the code was written wasn't standard.  This PR is just a retranslation of readme_zh.md,  I'm really sorry that my English is really poor, and the translation software may not be able to accurately express my will.  I hope you understand

### CODE REVIEW

**Comment by sunary** [comment]
This is PR already merged at: https://github.com/sunary/sqlize/pull/36, please rebase your branch

**Comment by liushuai05** [comment]
> This is PR already merged at: #36, please rebase your branch

Ok, you mean improve-liushuai05 branch

**Comment by sunary** [comment]
Sorry do not clear for you, I mean you need to rebase your branch. Could I close this, because I create the new one: https://github.com/sunary/sqlize/pull/40

**Comment by liushuai05** [comment]
> 
Of course, thank you for your patience and adjustment and optimization of my code.  Maybe my experience is not enough.

**Pull request closed without merging**
